config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :courses

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  layout 'admin'

  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :load_model, only: %i[edit update show destroy]

  def index
    @courses = Course.order(:name)
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new course_params
    if @course.save
      redirect_to courses_path, notice: 'Курс создан успешно'
    else
      render :new
    end
  end

  def update
    if @course.update course_params
      redirect_to courses_path
    else
      render :edit
    end
  end

  private

  def load_model
    @course = Course.find params[:id]
  end

  def course_params
    params.require(:course).permit(:name, :duration, :last_set, :next_set)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_model, only: %i[edit update show destroy]

  def index
    @users = User.order(:name)
  end

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to users_path, notice: "Пользователь создан успешно"
    else
      render :new
    end
  end

  def update
    if @user.update user_params
      redirect_to users_path
    else
      render :edit
    end
  end

  private

  def load_model
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:name, :email, :contacts, :comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/edit.html.haml
%h1 Редактировать курс

= simple_form_for @course, html: { id: 'user_form', class: 'form-horizontal', role: 'form' } do |f|
  = f.input :name, label: 'Название', autofocus: true
  = f.input :duration, label: 'Длительность'
  = f.input :last_set, label: 'Дата последнего набора'
  = f.input :next_set, label: 'Дата следующего набора'
  .form-group
    .col-sm-offset-3.col-sm-9
      = f.submit 'Сохранить', class: 'btn btn-primary'
      = link_to 'Отмена', courses_path, class: 'btn btn-default'

app/views/courses/index.html.haml
= link_to 'Добавить', new_course_path, class: 'btn btn-primary'

%h1 Курсы

%table.table.table-bordered.table-condensed.table-hover
  %tr
    %th
      \#
    %th
      Название
    %th
      Длительность
    %th
      Дата последнего набор
    %th
      Дата следующего набора
    %th

  - @courses.each_with_index do |course, index|
    %tr
      %td
        = index + 1
      %td
        = course.name
      %td
        = course.duration
      %td
        = course.last_set
      %td
        = course.next_set
      %td

app/views/courses/new.html.haml
%h1 Новый курс

= simple_form_for @course, html: { id: 'user_form', class: 'form-horizontal', role: 'form' } do |f|
  = f.input :name, label: 'Название', autofocus: true
  = f.input :duration, label: 'Длительность'
  = f.input :last_set, label: 'Дата последнего набора'
  = f.input :next_set, label: 'Дата следующего набора'
  .form-group
    .col-sm-offset-3.col-sm-9
      = f.submit 'Сохранить', class: 'btn btn-primary'
      = link_to 'Отмена', courses_path, class: 'btn btn-default'

app/views/layouts/_main_menu.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{role: 'navigation'}
  .container
    .navbar-header
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.dropdown
          %ul.dropdown-menu
            %li= link_to 'Пользователи', users_path
            %li= link_to 'Курсы', courses_path

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta(charset="utf-8")
    %title Eduson
    = stylesheet_link_tag    'admin', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render partial: 'layouts/main_menu'
    -#= render partial: 'shared/top_bar'
    -#= render partial: 'shared/flash_messages'
    -#= render partial: 'shared/layout_js'
    .container
      .page-content
        -#= render partial: 'layouts/flash_messages'
        = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eduson</title>
    <%= csrf_meta_tags %>

<<<<<<< HEAD
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
=======
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
>>>>>>> 0e9470dfc6daf03fb11b7ef5e4713998f92af27d
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.haml
%h1 Редактировать пользователя

= simple_form_for @user, html: { id: 'user_form', class: 'form-horizontal', role: 'form' } do |f|
  = f.input :name, label: 'Имя', autofocus: true
  = f.input :email, label: 'Email'
  = f.input :contacts, label: 'Контакты'
  = f.input :comment, label: 'Примечание'
  .form-group
    .col-sm-offset-3.col-sm-9
      = f.submit 'Сохранить', class: 'btn btn-primary'
      = link_to 'Отмена', users_path, class: 'btn btn-default'

app/views/users/index.html.haml
= link_to 'Добавить', new_user_path, class: 'btn btn-primary'

%h1 Пользователи

%table.table.table-bordered.table-condensed.table-hover
  %tr
    %th
      \#
    %th
      Имя
    %th
      Email
    %th
      Контакты
    %th
      Примечания
    %th

  - @users.each_with_index do |user, index|
    %tr
      %td
        = index + 1
      %td
        = user.name
      %td
        = user.email
      %td
        = user.contacts
      %td
        = user.comment
      %td

app/views/users/new.html.haml
%h1 Новый пользователь

= simple_form_for @user, html: { id: 'user_form', class: 'form-horizontal', role: 'form' } do |f|
  = f.input :name, label: 'Имя', autofocus: true
  = f.input :email, label: 'Email'
  = f.input :contacts, label: 'Контакты'
  = f.input :comment, label: 'Примечание'
  .form-group
    .col-sm-offset-3.col-sm-9
      = f.submit 'Сохранить', class: 'btn btn-primary'
      = link_to 'Отмена', users_path, class: 'btn btn-default'